version: '3.7'
services:
  webserver:
    build:
      context: ..
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - proxy
  proxy:
    build:
      context: ..
      dockerfile: trafficCaptureProxyServer/Proxy.Dockerfile
    ports:
      - "9201:9201"
    environment:
      BACKSIDE_HOST: webserver
      BACKSIDE_PORT: 80
      BIND_PORT: 9201

  jmeter:
    build:
      context: ..
      dockerfile: JMeter/JMeter.Dockerfile
    depends_on:
      - webserver
    environment:
      DOMAIN_NAME: proxy
      BIND_PORT: 9201

networks:
  my-net:
    driver: bridge
