name: CI

on:
  [push, pull_request]:
    paths:
      - 'cluster_migration_core/**'
      - 'cluster_traffic_capture/**'
      - 'index_configuration_tool/**'
      - 'test/**'
      - 'upgrades/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Analysing the code with flake8
        run: |
          flake8 $(git ls-files '*.py')
